# Generated by Django 6.0.7 on 2026-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço completo'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
