# Generated by Django 6.0.7 on 2026-07-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_producerprofile_address_producerprofile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rótulo (Casa, Trabalho...)'),
        ),
    ]
