# Generated by Django 6.0.7 on 2026-07-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientaddress_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'ordering': ['-is_default', '-id']},
        ),
    ]
